config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: "registrations"}
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'tags/:tag', to: 'articles#index', as: :tag
  resources :articles do
    resources :comments
  end 
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }

  def self.tagged_with(name)
    Tag.find_by!(name: name).articles
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource_or_scope)
    articles_url
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def new
	@article = Article.new
end

def edit
	@article = Article.find(params[:id])
end

def update
	@article = Article.find(params[:id])

	if @article.update(params_article)
		redirect_to @article
	else
		render 'edit'
	end
end

def destroy
	@article = Article.find(params[:id])
	@article.destroy

	redirect_to articles_path
end

def create
	# render plain: params[:article].inspect
	@article = Article.new(params_article)
	
	if @article.save
		redirect_to @article
	else
		render 'new'
	end
end

def show
	@article = Article.find(params[:id])
	respond_to do |format|
   format.html
   format.pdf do
     render pdf: "diary_article",
     template: "articles/show.html.erb",
     layout: 'pdf.html',
     encoding: 'utf8'
   	end
   end
end

def index
	if params[:tag]
		@article = Article.tagged_with(params[:tag]).order(created_at: :desc).page(params[:page])
	else
		@article = Article.all.order(created_at: :desc).page params[:page]
	# @article.order(:date).page params[:page]
	end
end

private

def params_article
	params.require(:article).permit(:title, :text, :tag_list)
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
  @article = Article.find(params[:article_id])
  @comment = @article.comments.create(comment_params)
  redirect_to article_path(@article)
end

def destroy
  @article = Article.find(params[:article_id])
  @comment = @article.comments.find(params[:id])
  @comment.destroy  
  redirect_to article_path(@article)
end

private

def comment_params
  params.require(:comment).permit(:commenter, :body)
end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]
  
  protected

  def one_user_registered?
    if User.count == 1
      if user_signed_in?
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end  
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/_sidebar.html.erb
<div class="sidebar-column">
  <div class="navigation-bar w-nav" data-animation="default" data-collapse="medium" data-contain="1" data-duration="400">
    <div class="w-container">
      <h1><%= link_to "Diary", root_path, class:"logo-link w-nav-brand logo-text" %>  </h1>
      <nav class="navigation-menu w-nav-menu" role="navigation">
        <p class="main-subheading w-hidden-medium w-hidden-small w-hidden-tiny">A secret diary for one person. No visitors and readers. All that is written can read only you.</p>
        <div class="divider w-hidden-medium w-hidden-small w-hidden-tiny"></div>
        <a class="nav-link w-nav-link" href="/about">About</a>
        <a class="nav-link w-nav-link" href="/contact">Profile</a>
        <a><%= link_to 'New post', new_article_path, class:"nav-link w-nav-link" %></a>
        <a><%= link_to "All Posts", root_path, class:"nav-link w-navli-nk" %></a>
        <a class="nav-link w-nav-link" href="/contact">Settings</a>
        <a><%= link_to "Logout", destroy_user_session_path, 
                method: :delete, class:"nav-link w-navli-nk"%> </a>
      </nav>
      <div class="menu-button w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
</div>s

app/views/articles/edit.html.erb
<%= render 'sidebar' %>

<div class="content">
  <div class="form-wrapper w-form">
    <%= form_with model: @article, local: true do |form| %>
    <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div>
      <div class="body-copy w-richtext">
        <h1>Editing article</h1>
      </div>
    </div>
    <form data-name="Email Form" id="email-form" name="email-form">
      <label for="Name">Title</label>
      <%= form.text_field :title, class:"text-field w-input" %>
      <label for="Message">Message</label><p>
      <%= cktext_area :article, :text, cols: 40 %></p>
      <%= link_to 'Back', articles_path, class:"button w-button" %>
      <%= form.submit 'Save the post', class:"button w-button" %>
      <% end %>
    </form>
  </div>
</div>

app/views/articles/index.html.erb
<%= render 'sidebar' %>

<div class="content">
<% @article.each do |article| %>
<%= paginate @article %>
  <div class="blog-list w-dyn-list">
    <div class="w-dyn-items">
      <div class="w-dyn-item">
        <div class="post-wrapper">
          <a><h1><%= link_to article.title, article_path(article), class: "blog-title-link w-inline-block blog-title" %></h1></a>
          <div class="post-info-wrapper">
            <div class="post-info"><%= article.created_at.strftime("%d-%m-%y")%></div>
            <div class="post-info"> | </div>
            <div class="post-info"><%= raw article.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
            </div>
          </div>
          <div class="post-summary">
          <%=truncate(article.text, length: 250, escape: false)%>
          </div>
          <a><%= link_to 'Continue reading →', article_path(article), class: "button-round w-button" %>
          </a>
        </div>
      </div>
    </div>
  </div>
<% end %>
  <div class="button-wrapper button-left"><a><%= link_to_previous_page @article, '← Previous', class: "button w-button"%></a></div>
  <div class="button-wrapper button-right"><a><%= link_to_next_page @article, 'Next →', class: "button w-button"%></a></div>
</div>

app/views/articles/new.html.erb
<%= render 'sidebar' %>

<div class="content">
  <div class="form-wrapper w-form">
    <%= form_with model: @article, local: true do |form| %>
    <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div>
      <div class="body-copy w-richtext">
        <h1>New article</h1>
      </div>
    </div>
    <form data-name="Email Form" id="email-form" name="email-form">
      <label for="Name">Title</label>
      <%= form.text_field :title, class:"text-field w-input" %>
      <label for="Message">Message</label><p>
      <%= cktext_area :article, :text, cols: 40 %></p>
      <label for="Tags">Tags</label>
      <%= form.text_field :tag_list, placeholder: "Tags separated with comma", class:"text-field w-input" %>
      <%= form.submit 'Add the post', class:"button w-button" %>
      <% end %>
    </form>
  </div>
</div>

app/views/articles/show.html.erb
<%= render 'sidebar' %>
<div class="content">
  <div class="w-container">
    <div class="post-title-section">
      <h1><%= @article.title %></h1>
      <div class="post-info-wrapper">
        <div class="post-info"><%= @article.created_at.strftime("%d-%m-%y")%></div>
        <div class="post-info">|</div>
        <a class="post-info when-link" href="/categories/travel">Travel</a>
      </div>
    </div>
    <div class="body-copy w-richtext">
      <p><%= @article.text.html_safe %></p>
    </div>
  </div>
  <div class="post-info-wrapper">
    <div class="button-wrapper">
      <%= link_to 'Back', articles_path, class:"button w-button" %>
      <%= link_to 'Create PDF document', article_path(@article, :format => :pdf), 
                                          class:"button w-button" %>
      <%= link_to 'Edit', edit_article_path(@article), class:"button w-button" %>
      <%= link_to 'Delete', article_path(@article), class:"button w-button", 
                                method: :delete,
                                data: {confirm: 'Are you sure?'} %>
    </div>
  </div>
</div>
<!-- <h2>Comments</h2>
<%= render @article.comments %>
  
<h2>Add a comment:</h2>
<%= render 'comments/form' %> -->

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy comment', [comment.article, comment],
               method: :delete,
               data: {confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='//cdn.ckeditor.com/4.7.1/standard/ckeditor.js'</script>
    <script type="text/javascript">WebFont.load({
  google: {
    families: ["Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic","Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic","Fjalla One:regular"]
  }
});</script>

  </head>

  <body>
  <div id="header">
  <% if user_signed_in? %>
   <%= link_to('logout', destroy_user_session_path, method: :delete) %>
   <%= link_to('edit', edit_user_registration_path) %>
  <% else %>
  <%= link_to('login', new_user_session_path) %>
  <% end %>
</div>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<title>Diary post</title>
  <%= wicked_pdf_stylesheet_link_tag "application" %>
</head>
<body>
  <div align="center" class="post-wrapper">
    <h2><%= @article.title %></h2>
  </div>
  <p class="block-with-text">
    <%= @article.text.html_safe %>
  </p>

app/views/shared/_links.html.erb
<ul>
  <% if user_signed_in? %>
    <li><%= link_to "My Profile", edit_user_registration_path%> </li>
    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete%> </li>
  <% else %>
    <li><%= link_to "Sign up", new_user_registration_path%> </li>
    <li><%= link_to "Sign in", new_user_session_path%> </li>
  <% end %>
</ul>   

app/views/welcome/index.html.erb
<div align="center"><h1>Hello</h1>
<%=link_to 'My blog', controller: 'articles' %>
</div>